public enum ArenaStage
{
    WAITING_FOR_POKEMONS,
    TEAM0_DECISION,
    TEAM1_DECISION,
    COMBAT_INIT,
    TEAM0_STATUS_RESOLVE,
    TEAM1_STATUS_RESOLVE,
    FIRST_COMBAT_COMPUTE,
    FIRST_COMBAT_ANIMATION,
    SECOND_COMBAT_COMPUTE,
    SECOND_COMBAT_ANIMATION,
    CONCLUSION
}
